name: urbaneye_mobile
description: UrbanEye Citizen Reporting System - Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Networking
  http: ^1.2.0
  http_parser: ^4.0.2

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Camera & Image
  camera: ^0.11.0+1
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0

  # Location
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Voice / Speech
  speech_to_text: ^7.3.0

  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Utils
  intl: ^0.19.0
  path: ^1.8.3
  mime: ^1.0.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
